# Generated by Django 5.2.4 on 2025-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('check-in', 'Check-in'), ('check-out', 'Check-out')], max_length=10)),
                ('rig_id', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rig_id', 'timestamp'], name='checkin_che_rig_id_e401ba_idx'), models.Index(fields=['record_id'], name='checkin_che_record__c2b37f_idx')],
            },
        ),
    ]
