services:
  db:
    image: postgres:17-alpine3.22
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/web
      - staticvol:/web/staticfiles
      - templates:/web/templates
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:8000
    volumes:
      - staticvol:/vol/static


volumes:
  pgdata:
  staticvol:
  templates: